In [63]:
# Data packages
import pandas as pd
import numpy as np

# ML / Classification packages
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.dummy import DummyClassifier

# Visualization packages
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

In [64]:
default_risk = pd.read_csv(r"C:\Users\germs\Documents\Projects\WGU\Capstone\data\Loan_Default.csv")
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.expand_frame_repr", False)

default_risk.head()

      ID  year loan_limit             Gender approv_in_adv loan_type loan_purpose Credit_Worthiness open_credit business_or_commercial  loan_amount  rate_of_interest  Interest_rate_spread  Upfront_charges   term Neg_ammortization interest_only lump_sum_payment  property_value construction_type occupancy_type Secured_by total_units   income credit_type  Credit_Score co-applicant_credit_type    age submission_of_application        LTV Region Security_Type  Status  dtir1
0  24890  2019         cf  Sex Not Available         nopre     type1           p1                l1        nopc                  nob/c       116500               NaN                   NaN              NaN  360.0           not_neg       not_int         not_lpsm        118000.0                sb             pr       home          1U   1740.0         EXP           758                      CIB  25-34                   to_inst  98.728814  south        direct       1   45.0
1  24891  2019         cf               Male         nopre     type2           p1                l1        nopc                    b/c       206500               NaN                   NaN              NaN  360.0           not_neg       not_int             lpsm             NaN                sb             pr       home          1U   4980.0        EQUI           552                      EXP  55-64                   to_inst        NaN  North        direct       1    NaN
2  24892  2019         cf               Male           pre     type1           p1                l1        nopc                  nob/c       406500              4.56                0.2000            595.0  360.0           neg_amm       not_int         not_lpsm        508000.0                sb             pr       home          1U   9480.0         EXP           834                      CIB  35-44                   to_inst  80.019685  south        direct       0   46.0
3  24893  2019         cf               Male         nopre     type1           p4                l1        nopc                  nob/c       456500              4.25                0.6810              NaN  360.0           not_neg       not_int         not_lpsm        658000.0                sb             pr       home          1U  11880.0         EXP           587                      CIB  45-54                  not_inst  69.376900  North        direct       0   42.0
4  24894  2019         cf              Joint           pre     type1           p1                l1        nopc                  nob/c       696500              4.00                0.3042              0.0  360.0           not_neg       not_int         not_lpsm        758000.0                sb             pr       home          1U  10440.0        CRIF           602                      EXP  25-34                  not_inst  91.886544  North        direct       0   39.0

In [65]:
default_risk.describe(include='all')

                   ID      year loan_limit  Gender approv_in_adv loan_type loan_purpose Credit_Worthiness open_credit business_or_commercial   loan_amount  rate_of_interest  Interest_rate_spread  Upfront_charges           term Neg_ammortization interest_only lump_sum_payment  property_value construction_type occupancy_type Secured_by total_units         income credit_type   Credit_Score co-applicant_credit_type     age submission_of_application            LTV  Region Security_Type         Status          dtir1
count   148670.000000  148670.0     145326  148670        147762    148670       148536            148670      148670                 148670  1.486700e+05     112231.000000         112031.000000    109028.000000  148629.000000            148549        148670           148670    1.335720e+05            148670         148670     148670      148670  139520.000000      148670  148670.000000                   148670  148470                    148470  133572.000000  148670        148670  148670.000000  124549.000000
unique            NaN       NaN          2       4             2         3            4                 2           2                      2           NaN               NaN                   NaN              NaN            NaN                 2             2                2             NaN                 2              3          2           4            NaN           4            NaN                        2       7                         2            NaN       4             2            NaN            NaN
top               NaN       NaN         cf    Male         nopre     type1           p3                l1        nopc                  nob/c           NaN               NaN                   NaN              NaN            NaN           not_neg       not_int         not_lpsm             NaN                sb             pr       home          1U            NaN         CIB            NaN                      CIB   45-54                   to_inst            NaN   North        direct            NaN            NaN
freq              NaN       NaN     135348   42346        124621    113173        55934            142344      148114                 127908           NaN               NaN                   NaN              NaN            NaN            133420        141560           145286             NaN            148637         138201     148637      146480            NaN       48152            NaN                    74392   34720                     95814            NaN   74722        148637            NaN            NaN
mean     99224.500000    2019.0        NaN     NaN           NaN       NaN          NaN               NaN         NaN                    NaN  3.311177e+05          4.045476              0.441656      3224.996127     335.136582               NaN           NaN              NaN    4.978935e+05               NaN            NaN        NaN         NaN    6957.338876         NaN     699.789103                      NaN     NaN                       NaN      72.746457     NaN           NaN       0.246445      37.732932
std      42917.476598       0.0        NaN     NaN           NaN       NaN          NaN               NaN         NaN                    NaN  1.839093e+05          0.561391              0.513043      3251.121510      58.409084               NaN           NaN              NaN    3.599353e+05               NaN            NaN        NaN         NaN    6496.586382         NaN     115.875857                      NaN     NaN                       NaN      39.967603     NaN           NaN       0.430942      10.545435
min      24890.000000    2019.0        NaN     NaN           NaN       NaN          NaN               NaN         NaN                    NaN  1.650000e+04          0.000000             -3.638000         0.000000      96.000000               NaN           NaN              NaN    8.000000e+03               NaN            NaN        NaN         NaN       0.000000         NaN     500.000000                      NaN     NaN                       NaN       0.967478     NaN           NaN       0.000000       5.000000
25%      62057.250000    2019.0        NaN     NaN           NaN       NaN          NaN               NaN         NaN                    NaN  1.965000e+05          3.625000              0.076000       581.490000     360.000000               NaN           NaN              NaN    2.680000e+05               NaN            NaN        NaN         NaN    3720.000000         NaN     599.000000                      NaN     NaN                       NaN      60.474860     NaN           NaN       0.000000      31.000000
50%      99224.500000    2019.0        NaN     NaN           NaN       NaN          NaN               NaN         NaN                    NaN  2.965000e+05          3.990000              0.390400      2596.450000     360.000000               NaN           NaN              NaN    4.180000e+05               NaN            NaN        NaN         NaN    5760.000000         NaN     699.000000                      NaN     NaN                       NaN      75.135870     NaN           NaN       0.000000      39.000000
75%     136391.750000    2019.0        NaN     NaN           NaN       NaN          NaN               NaN         NaN                    NaN  4.365000e+05          4.375000              0.775400      4812.500000     360.000000               NaN           NaN              NaN    6.280000e+05               NaN            NaN        NaN         NaN    8520.000000         NaN     800.000000                      NaN     NaN                       NaN      86.184211     NaN           NaN       0.000000      45.000000
max     173559.000000    2019.0        NaN     NaN           NaN       NaN          NaN               NaN         NaN                    NaN  3.576500e+06          8.000000              3.357000     60000.000000     360.000000               NaN           NaN              NaN    1.650800e+07               NaN            NaN        NaN         NaN  578580.000000         NaN     900.000000                      NaN     NaN                       NaN    7831.250000     NaN           NaN       1.000000      61.000000

# Data Cleaning and Validation

The Equal Credit Opportunity Act prohibits discrimination in lending based on certain protected characteristics such as race, gender, religion, and age.

Columns related to these protected characteristics should not be used in the training model.

#### Gender

Our dataset includes a gender column that serves a dual purpose: indicating whether this is a joint application or not. The amount of borrowers can have a measurable impact on credit worthiness and the probability of default. Therefore, we will want to extract instances where a loan is marked as joint into a separate column and then delete the 'Gender' column altogether.

In [66]:
# Create a copy for training
default_risk_train = default_risk.copy()

# Extract joint application column
default_risk_train['joint_application'] = default_risk_train['Gender'].apply(lambda x: 1 if x == 'Joint' else 0)

# Drop protected characteristics
default_risk_train = default_risk_train.drop(columns=['Gender', 'age'])

# Drop identifier columns
default_risk_train = default_risk_train.drop(columns=['ID'])

# Drop columns with constant or near-constant values
constant_columns = [col for col in default_risk_train.columns if default_risk_train[col].nunique() == 1]
quasi_constant_columns = [col for col in default_risk_train.columns if default_risk_train[col].value_counts(normalize=True, dropna=False).iloc[0] > 0.96 and col not in constant_columns]

print("Columns with constant values to drop from training model:", constant_columns)
print("Columns with near-constant values (>96% single category):", quasi_constant_columns)

default_risk_train = default_risk_train.drop(columns=constant_columns + quasi_constant_columns)
default_risk_train.head()

Columns with constant values to drop from training model: ['year']
Columns with near-constant values (>96% single category): ['open_credit', 'lump_sum_payment', 'construction_type', 'Secured_by', 'total_units', 'Security_Type']

  loan_limit approv_in_adv loan_type loan_purpose Credit_Worthiness business_or_commercial  loan_amount  rate_of_interest  Interest_rate_spread  Upfront_charges   term Neg_ammortization interest_only  property_value occupancy_type   income credit_type  Credit_Score co-applicant_credit_type submission_of_application        LTV Region  Status  dtir1  joint_application
0         cf         nopre     type1           p1                l1                  nob/c       116500               NaN                   NaN              NaN  360.0           not_neg       not_int        118000.0             pr   1740.0         EXP           758                      CIB                   to_inst  98.728814  south       1   45.0                  0
1         cf         nopre     type2           p1                l1                    b/c       206500               NaN                   NaN              NaN  360.0           not_neg       not_int             NaN             pr   4980.0        EQUI           552                      EXP                   to_inst        NaN  North       1    NaN                  0
2         cf           pre     type1           p1                l1                  nob/c       406500              4.56                0.2000            595.0  360.0           neg_amm       not_int        508000.0             pr   9480.0         EXP           834                      CIB                   to_inst  80.019685  south       0   46.0                  0
3         cf         nopre     type1           p4                l1                  nob/c       456500              4.25                0.6810              NaN  360.0           not_neg       not_int        658000.0             pr  11880.0         EXP           587                      CIB                  not_inst  69.376900  North       0   42.0                  0
4         cf           pre     type1           p1                l1                  nob/c       696500              4.00                0.3042              0.0  360.0           not_neg       not_int        758000.0             pr  10440.0        CRIF           602                      EXP                  not_inst  91.886544  North       0   39.0                  1

#### Imputing Missing Values and One-Hot Encoding Categorical Variables

One-Hot Encoding is a technique used to convert categorical variables into a format that can be provided to machine learning algorithms to improve prediction accuracy. This is necessary because most machine learning algorithms work best with numerical data. One-Hot Encoding creates new binary columns for each category in a categorical variable, with a value of 1 indicating the presence of the category and 0 indicating its absence.

Before this, we need to handle missing values in the dataset. Missing values can cause issues in machine learning models, so it's important to address them before proceeding with data preprocessing. We will use the SimpleImputer from Scikit-Learn to fill in missing values with the median for numerical columns and "Unknown" categorical columns.

This will be implemented here using the Scikit-Learn Pipeline, which allows for a sequence of data processing steps to be chained together. This will help to streamline the data preprocessing pipeline and make it easier to manage and maintain.

In [69]:
# Select categorical columns
categorical_columns = default_risk_train.select_dtypes(include=['object']).columns
numerical_columns = default_risk_train.select_dtypes(include=['number']).columns

# Define the categorical pipeline to impute NaNs with 'Unknown' and then pipe to One-Hot Encode
cat_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='Unknown')),
    ('encoder', OneHotEncoder(sparse_output=False, handle_unknown='ignore'))
])

# Define the numerical pipeline to impute NaNs with the median
num_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median'))
])

# Combine pipelines into a ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
    ('cat', cat_pipeline, categorical_columns),
    ('num', num_pipeline, numerical_columns)
    ],
    remainder='passthrough'
)

# Configure transformer to output a Pandas DataFrame
preprocessor.set_output(transform='pandas')

# Fix and transform data
default_risk_train = preprocessor.fit_transform(default_risk_train)

# # Convert to binary
# encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
#
# encoded_data = encoder.fit_transform(default_risk_train[categorical_columns])
#
# encoded_default_risk_train = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(categorical_columns))
#
# default_risk_train = pd.concat([default_risk_train.drop(columns=categorical_columns), encoded_default_risk_train], axis=1)

print("Imputation and One-Hot Encoding complete:")
display(default_risk_train.head())

Imputation and One-Hot Encoding complete:

   num__cat__loan_limit_Unknown  num__cat__loan_limit_cf  num__cat__loan_limit_ncf  num__cat__approv_in_adv_Unknown  num__cat__approv_in_adv_nopre  num__cat__approv_in_adv_pre  num__cat__loan_type_type1  num__cat__loan_type_type2  num__cat__loan_type_type3  num__cat__loan_purpose_Unknown  num__cat__loan_purpose_p1  num__cat__loan_purpose_p2  num__cat__loan_purpose_p3  num__cat__loan_purpose_p4  num__cat__Credit_Worthiness_l1  num__cat__Credit_Worthiness_l2  num__cat__business_or_commercial_b/c  num__cat__business_or_commercial_nob/c  num__cat__Neg_ammortization_Unknown  num__cat__Neg_ammortization_neg_amm  num__cat__Neg_ammortization_not_neg  num__cat__interest_only_int_only  num__cat__interest_only_not_int  num__cat__occupancy_type_ir  num__cat__occupancy_type_pr  num__cat__occupancy_type_sr  num__cat__credit_type_CIB  num__cat__credit_type_CRIF  num__cat__credit_type_EQUI  num__cat__credit_type_EXP  num__cat__co-applicant_credit_type_CIB  num__cat__co-applicant_credit_type_EXP  num__cat__submission_of_application_Unknown  num__cat__submission_of_application_not_inst  num__cat__submission_of_application_to_inst  num__cat__Region_North  num__cat__Region_North-East  num__cat__Region_central  num__cat__Region_south  num__num__loan_amount  num__num__rate_of_interest  num__num__Interest_rate_spread  num__num__Upfront_charges  num__num__term  num__num__property_value  num__num__income  num__num__Credit_Score  num__num__LTV  num__num__Status  num__num__dtir1  num__num__joint_application
0                           0.0                      1.0                       0.0                              0.0                            1.0                          0.0                        1.0                        0.0                        0.0                             0.0                        1.0                        0.0                        0.0                        0.0                             1.0                             0.0                                   0.0                                     1.0                                  0.0                                  0.0                                  1.0                               0.0                              1.0                          0.0                          1.0                          0.0                        0.0                         0.0                         0.0                        1.0                                     1.0                                     0.0                                          0.0                                           0.0                                          1.0                     0.0                          0.0                       0.0                     1.0               116500.0                        3.99                          0.3904                    2596.45           360.0                  118000.0            1740.0                   758.0      98.728814               1.0             45.0                          0.0
1                           0.0                      1.0                       0.0                              0.0                            1.0                          0.0                        0.0                        1.0                        0.0                             0.0                        1.0                        0.0                        0.0                        0.0                             1.0                             0.0                                   1.0                                     0.0                                  0.0                                  0.0                                  1.0                               0.0                              1.0                          0.0                          1.0                          0.0                        0.0                         0.0                         1.0                        0.0                                     0.0                                     1.0                                          0.0                                           0.0                                          1.0                     1.0                          0.0                       0.0                     0.0               206500.0                        3.99                          0.3904                    2596.45           360.0                  418000.0            4980.0                   552.0      75.135870               1.0             39.0                          0.0
2                           0.0                      1.0                       0.0                              0.0                            0.0                          1.0                        1.0                        0.0                        0.0                             0.0                        1.0                        0.0                        0.0                        0.0                             1.0                             0.0                                   0.0                                     1.0                                  0.0                                  1.0                                  0.0                               0.0                              1.0                          0.0                          1.0                          0.0                        0.0                         0.0                         0.0                        1.0                                     1.0                                     0.0                                          0.0                                           0.0                                          1.0                     0.0                          0.0                       0.0                     1.0               406500.0                        4.56                          0.2000                     595.00           360.0                  508000.0            9480.0                   834.0      80.019685               0.0             46.0                          0.0
3                           0.0                      1.0                       0.0                              0.0                            1.0                          0.0                        1.0                        0.0                        0.0                             0.0                        0.0                        0.0                        0.0                        1.0                             1.0                             0.0                                   0.0                                     1.0                                  0.0                                  0.0                                  1.0                               0.0                              1.0                          0.0                          1.0                          0.0                        0.0                         0.0                         0.0                        1.0                                     1.0                                     0.0                                          0.0                                           1.0                                          0.0                     1.0                          0.0                       0.0                     0.0               456500.0                        4.25                          0.6810                    2596.45           360.0                  658000.0           11880.0                   587.0      69.376900               0.0             42.0                          0.0
4                           0.0                      1.0                       0.0                              0.0                            0.0                          1.0                        1.0                        0.0                        0.0                             0.0                        1.0                        0.0                        0.0                        0.0                             1.0                             0.0                                   0.0                                     1.0                                  0.0                                  0.0                                  1.0                               0.0                              1.0                          0.0                          1.0                          0.0                        0.0                         1.0                         0.0                        0.0                                     0.0                                     1.0                                          0.0                                           1.0                                          0.0                     1.0                          0.0                       0.0                     0.0               696500.0                        4.00                          0.3042                       0.00           360.0                  758000.0           10440.0                   602.0      91.886544               0.0             39.0                          1.0

In [68]:
default_risk_train.isna().sum().sort_values(ascending=False).head(20)

cat__loan_limit_Unknown              0
cat__loan_limit_cf                   0
cat__loan_limit_ncf                  0
cat__approv_in_adv_Unknown           0
cat__approv_in_adv_nopre             0
cat__approv_in_adv_pre               0
cat__loan_type_type1                 0
cat__loan_type_type2                 0
cat__loan_type_type3                 0
cat__loan_purpose_Unknown            0
cat__loan_purpose_p1                 0
cat__loan_purpose_p2                 0
cat__loan_purpose_p3                 0
cat__loan_purpose_p4                 0
cat__Credit_Worthiness_l1            0
cat__Credit_Worthiness_l2            0
cat__business_or_commercial_b/c      0
cat__business_or_commercial_nob/c    0
cat__Neg_ammortization_Unknown       0
cat__Neg_ammortization_neg_amm       0
dtype: int64